
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: keijiban_development

test:
  <<: *default
  database: keijiban_test

production:
  <<: *default
  database: keijiban_production
  username: keijiban
  password: <%= ENV['KEIJIBAN_DATABASE_PASSWORD'] %>